### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by bauen1** [parrot-opensource/ardrone-opensource#1]
The code for the AR.Parrot 1.0 and 2.0 appears to be missing (never got added after the migration to github)

**Comment by OpenUAS** [comment]
Sadly yes, Parrot is bound by GNU however, so still should provide the sources. For what **we** have found in archives, it added as a starter... @JeromeBouvard please add the remaining missing sources.

**Comment by JeromeBouvard** [comment]
we are working on it!
